from time import sleep
from selenium.webdriver import Edge, EdgeOptions
a = EdgeOptions()
a.add_experimental_option("detach", True)
driver = Edge(options=a)
driver.get("https://www.flipkart.com/")
driver.maximize_window()
sleep(2)
driver.switch_to.new_window()
driver.get("https://www.myntra.com/")
sleep(2)
driver.switch_to.new_window()
driver.get("https://www.amazon.in/")
sleep(2)
driver.switch_to.window(driver.window_handles[0])
print("Title of flipkart window is: ", driver.title)
print("URL of flipkart window is: ", driver.current_url)
sleep(3)
driver.switch_to.window(driver.window_handles[1])
print("Title of myntra window is: ", driver.title)
print("URL of myntra window is: ", driver.current_url)
sleep(3)
driver.switch_to.window(driver.window_handles[2])
print("Title of amazon window is: ", driver.title)
print("URL of amazon window is: ", driver.current_url)
sleep(2)
driver.switch_to.window(driver.window_handles[2])
driver.close()
sleep(2)
driver.switch_to.window(driver.window_handles[1])
driver.close()
sleep(2)
driver.switch_to.window(driver.window_handles[0])
driver.quit()